baseURL = "https://gastrohouse.sk"
disableHugoGeneratorInject = true
disableKinds = ["sitemap", "RSS"]
title = "Gastro House"
[[menu.footer]]
name = "Kontakt"
url = "/kontakt/"
weight = 2
[[menu.footer]]
name = "O nás"
url = "/o-nas/"
weight = 1
[[menu.main]]
name = "Kontakt"
url = "/kontakt/"
weight = 2
[[menu.main]]
name = "O nás"
url = "/o-nas/"
weight = 1
[[menu.secondary]]
name = "Denné menu"
url = "/#denne-menu"
weight = 2
[[menu.secondary]]
name = "Jedálny lístok"
url = "/jedalny-listok/"
weight = 1
[outputs]
home = ["HTML"]
page = ["HTML"]
[params.cloudinary]
default = 400
url = "https://res.cloudinary.com/gastrohouse/image/upload/q_auto:good"
widths = ["2000", "1900", "1800", "1700", "1600", "1500", "1400", "1300", "1200", "1100", "1000", "900", "800", "700", "600", "500", "400", "300", "200"]
[taxonomies]
category = ""
group = ""
tag = ""
