baseURL = "https://gastrohouse.sk"
disableHugoGeneratorInject = true
title = "Gastro House"
[[menu.footer]]
name = "Kontakt"
url = "/kontakt/"
weight = 2
[[menu.footer]]
name = "O nás"
url = "/o-nas/"
weight = 1
[[menu.main]]
name = "Kontakt"
url = "/kontakt/"
weight = 2
[[menu.main]]
name = "O nás"
url = "/o-nas/"
weight = 1
[[menu.secondary]]
name = "Denné menu"
url = "/#denne-menu"
weight = 2
[[menu.secondary]]
name = "Jedálny lístok"
url = "/jedalny-listok/"
weight = 1
[outputs]
home = ["HTML"]
page = ["HTML"]
[taxonomies]
category = ""
group = ""
tag = ""
