---
label: default
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: layout
  label: Layout
  type: text
  hidden: false
  default: ''
- name: permalink
  label: Permalink
  type: text
  hidden: false
  default: ''
pages:
- content/jedalny-listok.html
- content/kontakt.html
- content/o-nas.md
- content/sent.md
